### 요청 저장
GET http://localhost:8080/hello


# GET http://localhost:8080/api/cinemas/{id}

# GET http://localhost:8080/api/cinemas?page={}&size={}

# GET http://localhost:8080/api/cinemas?q={영화제목}&page={}&size={}


#POST http://localhost:8080/api/v1/ticket/create

### 영화 예매 생성
POST http://localhost:8080/api/reservations
Content-Type: application/json

{
  "memberId": 1,
  "screeningId": 101,
  "selections": [
    { "seatId": 2001, "ageGroup": "ADULT" },
    { "seatId": 2002, "ageGroup": "CHILD" }
  ]
}

### 영화 예매 확정
POST http://localhost:8080/api/reservations/101/confirm

### 영화 예매 취소
POST http://localhost:8080/api/reservations/101/cancel